name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.73.0
          cache: true
      - name: ESLint
        run: pixi run lint
      - name: Prettier
        run: pixi run format
      - name: Typos
        run: pixi run typos
